### PR TITLE
updating to coffeescript 2

### PR DESCRIPTION
**Pull request by davidhennemann**
I updated grunt-contrib-coffee to use coffeescript 2. Changed the version number to 2, because otherwise `npm update` would break existing applications using this plugin.

### CODE REVIEW

**Comment by davidhennemann** [comment]
I think the test runner broke?

**Comment by stuikomma** [comment]
The test fails with:
```
/home/travis/build/gruntjs/grunt-contrib-coffee/node_modules/coffeescript/lib/coffeescript/index.js:46
  CoffeeScript.run = function(code, options = {}) {
                                            ^
>> Got an unexpected exception from the coffee-script compiler. The original exception was: SyntaxError: Unexpected token =
>> (The coffee-script compiler should not raise unexpected exceptions. You can file this error as an issue of the coffee-script compiler: https://github.com/jashkenas/coffee-script/issues)
```

I think the error is in the node version. This test ran with version `v0.10.48`. http://coffeescript.org/#compatibility lists node 7.6+ as a requirement. So it does not make sense to run the tests with an older version of node. 

You need to remove older versions from appveyor.yml and .travis.yml. Probably you should first pull the latest https://github.com/gruntjs/grunt-contrib-internal and then make the customizations necessary.

**Comment by Mte90** [comment]
any hope for a merge of this one?

**Comment by Mte90** [comment]
Seems that I am not the only one waiting a lot this pull request approval.

**Comment by bergie** [comment]
Would be great to get this merged and released, as then users (like NoFlo) could update seamlessly to CoffeeScript 2. I'm not sure who is the maintainer of the module. Seems latest activity was by @vladikoff

**Comment by Mte90** [comment]
It is blocking too many project :-/

**Comment by vladikoff** [comment]
I shall take a look at this in a bit. Thanks for patience

**Comment by Mte90** [comment]
any updates for this one? I know that I am annoying but is important :-D

**Comment by vladikoff** [comment]
2.0.0 on npm! please let us know if there are any issues

**Pull request merged**
